# Modeling 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('trainDataFeatures.tsv', sep='\t', index_col=0)

In [3]:
columns = df.columns[3:]

In [4]:
columns

Index([u'review_length', u'good', u'awful', u'bad', u'amazing', u'awesome',
       u'terrible', u'boring', u'interesting'],
      dtype='object')

In [5]:
X = np.asarray(df[columns])

In [6]:
X

array([[2302,    0,    0, ...,    3,    0,    1],
       [ 946,    0,    0, ...,    0,    0,    0],
       [2449,    0,    0, ...,    0,    0,    1],
       ..., 
       [ 641,    0,    0, ...,    0,    0,    0],
       [1141,    0,    0, ...,    0,    0,    0],
       [ 942,    0,    0, ...,    0,    0,    0]])

In [7]:
y = np.asarray(df.sentiment.transpose())

In [8]:
y

array([1, 1, 0, ..., 0, 0, 1])

In [9]:
from sklearn.naive_bayes import MultinomialNB

In [10]:
nb = MultinomialNB()

In [11]:
nb.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
nb.predict(np.asarray(df[columns]))

array([0, 1, 0, ..., 1, 1, 1])

In [13]:
np.mean(nb.predict(np.asarray(df[columns])) == df.sentiment)

0.67023999999999995

## Make Kaggle submission with test data

In [14]:
test_data = pd.read_csv('testData.tsv', sep='\t')

In [15]:
test_data

id                                             review
0      12311_10  Naturally in a film who's main themes are of m...
1        8348_2  This movie is a disaster within a disaster fil...
2        5828_4  All in all, this is a movie for kids. We saw i...
3        7186_2  Afraid of the Dark left me with the impression...
4       12128_7  A very accurate depiction of small time mob li...
5        2913_8  ...as valuable as King Tut's tomb! (OK, maybe ...
6        4396_1  This has to be one of the biggest misfires eve...
7         395_2  This is one of those movies I watched, and won...
8       10616_1  The worst movie i've seen in years (and i've s...
9        9074_9  Five medical students (Kevin Bacon, David Labr...
10       9252_3  'The Mill on the Floss' was one of the lesser ...
11       9896_9  I just saw this film at the phoenix film festi...
12        574_4  \The Love Letter\" is one of those movies that...
13      11182_8  Another fantastic offering from the Monkey Isl...
14      11656_4  This was included on the disk \Shorts: Volume ...
15       2322_4  I'm not really much of an Abbott & Costello fa...
16       8703_1  This movie was dreadful. Biblically very inacc...
17       7483_1  I don't think I've ever gave something a 1/10 ...
18      6007_10  Excellent story-telling and cinematography. Po...
19      12424_4  I completely forgot that I'd seen this within ...
20       4672_1  I like action movies. I have a softspot for \B...
21      10841_3  This is one of the worst Sandra Bullock movie ...
22       8954_7  Watched this flick on Saturday afternoon cable...
23       7392_1  I went to see \TKIA\" with high expectations, ...
24      10288_8  All credit to writer/director Gilles Mimouni w...
25       5343_4  As a writing teacher, there are two ending I n...
26       4950_1  I don't know why this has gotten any decent re...
27       9257_4  This film was released in the UK under the nam...
28       8689_3  Uncle Fred Olen Ray once again gives us a litt...
29       4480_2  OK, it's watchable if you are sick in bed or h...
...         ...                                                ...
24970   6857_10  With \Anatomy\" the german film producers have...
24971   11091_8  This movie is one of my all-time favorites. I ...
24972    4167_2  I found Code 46 very disappointing. I thought ...
24973     679_4  Tamara Anderson and her family are moving once...
24974   10147_1  Now I've seen it all. Just when I thought it c...
24975    6875_1  In this movie everything possible was wrong an...
24976    923_10  Well every scene so perfectly presented. Never...
24977    6200_8  Sleeper Cell is what 24 should have been. 24 i...
24978    7208_8  Not for everyone, but I really like it. Nice e...
24979    5363_8  Set just before the Second World War, this is ...
24980    4067_8  Contains Spoiler The movie is a good action/co...
24981    1773_7  This is one of several period sea-faring yarns...
24982   1498_10  Hearkening back to those \Good Old Days\" of 1...
24983  10497_10  I thought this to be a pretty good example of ...
24984   3444_10  Seeing this film, or rather set of films, in m...
24985     588_2  I didn't like this movie for many reasons - VE...
24986    9678_9  I absolutely love this show!!!!!!!, Its basica...
24987    1983_9  eXistenZ combines director David Cronenberg's ...
24988    5012_3  this movie is allegedly a comedy.so where did ...
24989   12240_2  The Comebacks is a spoof on inspirational spor...
24990    5071_2  I'd love to write a little summary of this mov...
24991    5078_2  Obvious tailored vehicle for Ryan Philippe. It...
24992   10069_3  <br /><br />JURASSIC PARK III *___ Adventure <...
24993    7407_8  If you're even mildly interested in the War be...
24994    7207_1  It used to be that video distributors like Sub...
24995   2155_10  Sony Pictures Classics, I'm looking at you! So...
24996     59_10  I always felt that Ms. Merkerson had never got...
24997    2531_1  I was so disappointed in this movie. I am v

In [16]:
test_data['review_length'] = test_data.review.apply(len)

In [17]:
# Do the same feature extraction with the test data

from sklearn.feature_extraction.text import CountVectorizer
vocab_expand = ['awesome', 'good', 'amazing', 'interesting', 'terrible', 'bad', 'awful','boring']
expand_vectorizer = CountVectorizer(vocabulary=vocab_expand)
bow_expand = expand_vectorizer.fit_transform(test_data.review).todense()
words_expand = list(expand_vectorizer.vocabulary_.keys())
bow_expand_df = pd.DataFrame(bow_expand, index=test_data.index, columns = words_expand)
test_data_expand = test_data.join(bow_expand_df)
test_data_expand.to_csv('testDataFeatures.tsv', sep='\t')

In [18]:
predictions = nb.predict(np.asarray(test_data_expand[columns]))

In [19]:
submission = pd.DataFrame({"id": test_data.id, "sentiment": predictions})

In [20]:
submission

id  sentiment
0      12311_10          1
1        8348_2          0
2        5828_4          1
3        7186_2          1
4       12128_7          1
5        2913_8          1
6        4396_1          1
7         395_2          0
8       10616_1          0
9        9074_9          1
10       9252_3          1
11       9896_9          1
12        574_4          1
13      11182_8          1
14      11656_4          1
15       2322_4          1
16       8703_1          1
17       7483_1          0
18      6007_10          1
19      12424_4          1
20       4672_1          1
21      10841_3          0
22       8954_7          1
23       7392_1          1
24      10288_8          1
25       5343_4          1
26       4950_1          0
27       9257_4          1
28       8689_3          1
29       4480_2          1
...         ...        ...
24970   6857_10          1
24971   11091_8          1
24972    4167_2          1
24973     679_4          1
24974   10147_1          0
24975    6875_1          1
24976    923_10          1
24977    6200_8          1
24978    7208_8          1
24979    5363_8          1
24980    4067_8          1
24981    1773_7          1
24982   1498_10          1
24983  10497_10          1
24984   3444_10          1
24985     588_2          0
24986    9678_9          0
24987    1983_9          1
24988    5012_3          1
24989   12240_2          1
24990    5071_2          1
24991    5078_2          1
24992   10069_3          1
24993    7407_8          1
24994    7207_1          0
24995   2155_10          1
24996     59_10          1
24997    2531_1          1
24998    7772_8          1
24999  11465_10          1

[25000 rows x 2 columns]