# Ensemble

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Data preparation
data = pd.read_csv('trainDataFeatures.tsv', sep='\t', index_col=0)

columns = data.columns[3:]
X = np.asarray(data[columns])
y = np.asarray(data.sentiment.transpose())

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [3]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 10, min_samples_split = 10)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)

In [4]:
y_predict

array([0, 1, 1, ..., 0, 0, 0])

In [5]:
from sklearn.metrics import roc_auc_score, confusion_matrix

roc_auc_score(y_test, y_predict)

0.64873018560854834

In [6]:
confusion_matrix(y_test, y_predict)

array([[1796, 1391],
       [ 815, 2248]])

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 2, min_samples_split = 2)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)
roc_auc_score(y_test, y_predict)

0.60499938484585958

In [8]:
confusion_matrix(y_test, y_predict)

array([[1819, 1368],
       [1105, 1958]])

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(min_samples_leaf = 1, min_samples_split = 1)

rf.fit(X=X_train, y = y_train)
y_predict = rf.predict(X_test)
roc_auc_score(y_test, y_predict)

0.59522222430517535

In [10]:
confusion_matrix(y_test, y_predict)

array([[1842, 1345],
       [1187, 1876]])